// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ksxvuodwnhmwqfkppscj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzeHZ1b2R3bmhtd3Fma3Bwc2NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NTYwMDYsImV4cCI6MjA2NzUzMjAwNn0.VPxmyZlfQF6reTbxVHbBPMUPPFj4os_JoAdvzWi7jLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});